### PR TITLE
Add: Tech Learning Collective

### PR DESCRIPTION
**Pull request by fabacab**

### CODE REVIEW

**Comment by DarkDotFail** [comment]
Intriguing resource. Are any of your courses open source or otherwise available for the vetting of what you are teaching? Please add a PGP signed /mirrors.txt and I also may list you. https://dark.fail/spec/omg.txt

**Comment by onionltd** [comment]
Hey @fabacab, thank you for your contribution! Can you please rebase to the latest master before I merge your PR? If I'm not mistaken, doing "rebase and merge" now will strip away your commit signature.

Also, being a little nit-picky, can you remove the end slash in the url? You most likely used `oniontree-add` which doesn't trim the end slash automatically. I apologize for the annoyance, handling outside contributions is still a new thing for me.

**Comment by fabacab** [comment]
> Hey @fabacab, thank you for your contribution! Can you please rebase to the latest master before I merge your PR? If I'm not mistaken, doing "rebase and merge" now will strip away your commit signature.
> 
> Also, being a little nit-picky, can you remove the end slash in the url? You most likely used `oniontree-add` which doesn't trim the end slash automatically. I apologize for the annoyance, handling outside contributions is still a new thing for me.

@onionltd Done in 9708df502a9b55a45c57040c8376e85e6e8afbd7.

**Comment by onionltd** [comment]
Well that didn't work either. Your signature was stripped away. I had to amend and sign-off the commit with my own key and force push into the master. That's far from ideal, but that's on me to work it out. Your changes are published at http://onions53ehmf4q75.onion/services/techlearningcollective.html.

Thanks again for you contribution and apologies for the annoyance.

**Pull request merged**
